### ISSUE TITLE
[REVIEW] Open Materials Review

### ISSUE THREAD

**Issue by chatchavan** [journalovi/2024-luong-graphical-models#6]
### Instructions for Open Practices Chair
- If there is anything in the list below that you are unsure of, you can reply to this issue (after it has been created) and tag the responsible organizers. Organizers' Github IDs are listed on [People page](https://www.journalovi.org/people.html).
- If anything in the below list is missing (e.g. required paper sections, supplemental materials, etc), [mention](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#mentioning-people-and-teams) the authors on this issue and ask them to add those materials. Authors' Github IDs are listed at the top of `README.md`.
- Once authors have provided any missing material (or if no material is missing) and all requirements are met, close this issue.

### Open Materials Checklist
- [ ] Paper license is CC-BY
- [ ] The "Research materials" section in the paper exists.
- [ ] Links to supplements and materials are listed in at least the following locations:
   - [ ] Abstract (according to the [structured abstract requirement](https://www.journalovi.org/author-guide.html#abstract))
   - [ ] "Research materials" section of the paper.
- [ ] All links to repositories and materials in the paper can be reached.
- [ ] All materials are in repositories that meet the [FAIR principles](https://www.go-fair.org/fair-principles/) (e.g. OSF, Zenodo, etc). Non-long-term hosting solutions, such as Github or self-hosted websites, are acceptable only if they are also archived on a long term repository like OSF or Zenodo. One easy way to archive + DOI an existing Github repo is with Zenodo; see [here](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)
- [ ] Check that all other requirements under the [transparency section of the author guide](https://www.journalovi.org/author-guide.html#transparency-requirements) are fulfilled.

**Comment by abhsarma** [comment]
@vuluongj20 

Currently, the OSF repository that is included is not anonymously accessible by the public. To address this, please create an OSF registration (see [instructions](https://help.osf.io/article/162-start-a-registration#start-a-registration-from-an-existing-project-or-component-1)). Once this is complete, please update the URL in the paper and post it here as well. I can then complete the Open Materials Review.

**Comment by vuluongj20** [comment]
@abhsarma The server issue has been resolved! The public registration is now available at https://osf.io/5zwe9. I've updated the paper with the new URL.

**Comment by abhsarma** [comment]
thanks!

**Comment by abhsarma** [comment]
@vuluongj20 please find the open practices review below:

**License:** Please add a CC-BY or CC-BY-SA license to your [paper](https://www.journalovi.org/2024-luong-graphical-models/). Please also add a license to your OSF repository (Creative Commons or an [OSI-approved license](https://opensource.org/licenses)).

**Abstract:** Paper lacks an abstract (thereby no links to supplements and materials are present in the abstract. If you do not wish the abstract to be at the top, you may add it as a section at the end of the article. (When we publish your article, we will need an abstract as a part of the metadata for registering a DOI.)
Missing DOIs: Please add DOIs for the following: [2](https://doi.org/10.1016/C2009-0-27609-4), [8](https://doi.org/10.1109/TIT.1967.1054010), [10](https://doi.org/10.48550/arXiv.cs/0306050), [20](https://doi.org/10.1016/j.ipm.2005.09.002), [26](https://doi.org/10.1089/cmb.2006.13.394); [20] is linked but not to the actual publication link. I have provided the DOIs for these here (see the links above).

**Dataset:** Authors are using a public dataset, including citation. However, the link within the citation (http://lcg-www.uia.ac.be/conll2003/ner/) is broken. Please include a link to the dataset which is accessible. Moreover, this dataset consists of annotations (publicly available) on the original text (which has limited access due to copyright). The homepage of the dataset itself is also not persistent. I’d recommend the following suggestions:
If the authors did not use the copyrighted part in their work, they can include the public part in their OSF repository together with a file that provides appropriate credit to the data source.
If the authors used the copyrighted part, they can quote the build instructions from the dataset homepage in one of their README files either in their paper or on OSF.

**Comment by vuluongj20** [comment]
Hi @abhsarma, thank you for the detailed feedback and instructions!

**License:** I’ve added a CC-BY license to the OSF [project](https://osf.io/hvma6/) and [registration](https://osf.io/rqy5m/metadata/osf). The paper already contains a License section at the end with a CC-BY hyperlink. Is that sufficient or is there something else I need to do?
<img width="682" alt="Screenshot 2024-09-08 at 2 59 33 PM" src="https://github.com/user-attachments/assets/22d1bd6e-04f4-4a17-8c37-9c909ff8e5c4">

**Abstract:** The introduction (everything before “I. Probabilistic Graphical Models”) was meant to double as an abstract. I’ve added a subheading to make that more clear.
<img width="881" alt="Screenshot 2024-09-08 at 3 26 16 PM" src="https://github.com/user-attachments/assets/a3842afa-ac29-461d-a181-e8ecad14a35a">

**DOIs:** I’ve added the DOIs to the References section. Thank you for providing them!

**Dataset:** 
I’ve added a functioning download link to the Research Materials Statement section at the bottom of the article. It's the same source used by [Tensorflow Data.](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/text/conll2003/conll2003.py)￼
<img width="681" alt="Screenshot 2024-09-08 at 4 29 23 PM" src="https://github.com/user-attachments/assets/341e1427-9ad4-44c9-8dc3-861bee3bf51c">
We were not aware of the copyright issues. We used the annotations for both training and validation. I’ve removed the data files from the OSF project and added instructions for how to download the data in a root-level [README file](https://osf.io/hfsrq) and the project’s [Wiki](https://osf.io/rqy5m/wiki/home/). Since OSF doesn’t allow modifying files in a registration, I’ve withdrawn [the outdated registration](https://osf.io/5zwe9), created [a new one](https://osf.io/rqy5m), and updated the corresponding link in the article.

**Comment by abhsarma** [comment]
Hi @vuluongj20
Thanks for addressing the issues! Everything looks good to me.
